adding index page of Ecom website
rajaranjanmr/Ecom pull request #1
Opened 2022-02-18 21:40 UTC by rajaranjanmr

2022-02-18 22:08 UTC, malaykhakhar commented
While scrolling on homepage, the main container is getting over the navbar, and the navbar is visible below it. Rectify this for better user experience.

2022-02-19 04:18 UTC, malaykhakhar requested changes
While scrolling on homepage, the main container is getting over the navbar, and the navbar is visible below it. Rectify this for better user experience.

2022-02-19 06:17 UTC, malaykhakhar requested changes

2022-02-19 06:17 UTC, malaykhakhar commented on login/login.html
> +    <button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>
Remove comments which are not useful

2022-02-19 06:17 UTC, malaykhakhar commented on login/login.html
> +          </label>
Again, same issue with comments

2022-02-19 06:51 UTC, sri-rishi requested changes
Remove all comments form file

2022-02-19 06:51 UTC, sri-rishi commented on clhome.css
> +    border:1px solid grey;
use variable color naming

2022-02-19 06:51 UTC, sri-rishi commented on clhome.css
> +    color:white;
here also use variable color naming

2022-02-19 06:58 UTC, malaykhakhar approved these changes
Looks good

2022-02-19 13:47 UTC, sri-rishi approved these changes

2022-02-19 13:49 UTC, merged